Implemented player class
Frede175/HospitalGame pull request #14
Opened 2017-10-13 14:34 UTC by Frede175

A few things got added, that was not in the class before:
- getBloodType()
- dropItem(Command command)

One thing got changed:
- activeItems changed from ArrayList\<Item\> to  ArrayList\<PowerUpItem\>

2017-10-22 14:30 UTC, larsbjn requested changes
Is "actived" at line 108 correct spelled? Else I can't se anything wrong

2017-10-22 17:05 UTC, larsbjn approved these changes

2017-10-23 07:22 UTC, toszi requested changes

2017-10-23 07:22 UTC, toszi commented on src/hospitalgame/Player.java
> +        //Using iterator to loop though, since we need to be able to remove a item the from the list
spelling mistake

2017-10-23 07:26 UTC, toszi approved these changes

2017-10-23 07:26 UTC, merged