det meste af Item package implementeret
Frede175/HospitalGame pull request #15
Opened 2017-10-22 09:50 UTC by AndreasBoegh

under powerUpItem mangler update og startBuff

2017-10-22 10:01 UTC, frederikrosenberg requested changes
See addItem in inventory

2017-10-22 10:01 UTC, Frede175 commented on src/hospitalgame/item/Inventory.java
>      public boolean addItem(Item item) {
Is not checking if there is space for item in the inventory

2017-10-22 10:25 UTC, frederikrosenberg requested changes

2017-10-22 10:25 UTC, Frede175 commented on src/hospitalgame/item/Inventory.java
> +        } else { return false; }
Please do a format (Source -> format) i NetBeans

2017-10-22 10:31 UTC, frederikrosenberg approved these changes

2017-10-22 14:34 UTC, larsbjn requested changes
Maybe use for each loops instead of for loops

2017-10-22 14:34 UTC, larsbjn commented on src/hospitalgame/item/Inventory.java
> +        for (int i = 0; i <= inventory.size(); i++) {
Maybe a for each loop?

2017-10-22 14:34 UTC, larsbjn commented on src/hospitalgame/item/Inventory.java
> +        for (int i = 0; i < inventory.size(); i++) {
Again, maybe a for each loop?

2017-10-23 07:22 UTC, larsbjn approved these changes

2017-10-23 07:22 UTC, merged