Business implementation
Frede175/HospitalGame pull request #66
Opened 2017-11-27 15:27 UTC by AndreasBoegh

2017-11-27 18:35 UTC, frederikrosenberg requested changes
A lot of Javadoc needed

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/BusinessFacade.java
> +    private boolean isGameOver = false;
Variables need Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/BusinessFacade.java
>      void setGameOver(){
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/Inventory.java
>      }
Needs to set active items

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/Inventory.java
> +    public Item getItem(IItem item) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/Inventory.java
> +    public int hashCode() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/Inventory.java
> +    public int compareTo(Inventory o) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/Inventory.java
> +    public boolean equals(Object obj) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/ItemFacade.java
>          }
Remove obsolete code

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Item/ItemFacade.java
>      public IInventory[] getInventories() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
>      public void Map() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
>      public void injectItemFacade(IItemFacade itemFacade) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
>      public void InjectNPCFacade(INPCFacade npcFacade) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
>      public void generateMap(int roomCount, ArrayList<IItem> items, ArrayList<INPC> npcs) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
> +    private ArrayList<Room> createRooms(int roomCount) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
> +    public static List<String> pathfinder(Room startRoom, Room endRoom) {
Javadoc
Needs to return Directions

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Map.java
>      public IRoom[] getRooms(){
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Computer.java
> +    public String interact(IPlayer player) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Doctor.java
>      public void interact(Player player) {
Remove unused function

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Doctor.java
> +    public String interact(IPlayer player) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/NPC.java
> +    public abstract String interact(IPlayer player);
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/NPCFacade.java
> +    public void setRoom(INPC npc, IRoom room) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/NPCFacade.java
> +    public void setEndRoom(INPC npc, IRoom endRoom) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Porter.java
> +    private IRoom endRoom;
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Porter.java
>      public Porter(String name, boolean canMove, IRoom currentRoom, NPCID npcId) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Porter.java
>      public Porter(INPC npc) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/NPC/Porter.java
> +    public String interact(IPlayer player) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
> +    public void injectItemFacade(IItemFacade itemFacade) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public void setExit(Directions direction, IRoom roomNeighbour) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public boolean addItem(IItem item) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public boolean removeItem(IItem item) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public IItem getItem(int index) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
> +    public IRoom getExit(Directions direction) {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public String getName() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
> +    public Set<Directions> getExitDirections() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public boolean isLocked() {
Javadoc

2017-11-27 18:35 UTC, Frede175 commented on HospitalGame_Business/src/business/Room.java
>      public boolean isInspected() {
Javadoc

2017-11-28 13:36 UTC, frederikrosenberg requested changes

2017-11-28 13:36 UTC, Frede175 commented on HospitalGame_Business/src/business/Player.java
> +        this.name = player.getName();
Needs to set inventoryID and active items.

2017-11-28 14:14 UTC, frederikrosenberg approved these changes

2017-11-28 14:15 UTC, larsbjn approved these changes

2017-11-28 14:15 UTC, merged